name: pantab-dev
channels:
  - defaults
dependencies:
  - black
  - flake8
  - isort
  - mypy
  - pandas
  - pip
  - python
  - pytest
  - sphinx
  - sphinx_rtd_theme
  - pip:
    - asv
    - tableauhyperapi>=0.0.14567
